# Generated by Django 4.1.7 on 2023-03-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_lists_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='issue',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='need',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='repair',
            name='item',
            field=models.CharField(max_length=60),
        ),
    ]
